/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const FoodEntry = IDL.Record({
  'fat' : IDL.Nat,
  'fiber' : IDL.Nat,
  'carbohydrates' : IDL.Nat,
  'calories' : IDL.Nat,
  'description' : IDL.Text,
  'timestamp' : Time,
  'protein' : IDL.Nat,
});
export const NutritionTotals = IDL.Record({
  'fat' : IDL.Nat,
  'fiber' : IDL.Nat,
  'carbohydrates' : IDL.Nat,
  'calories' : IDL.Nat,
  'count' : IDL.Nat,
  'protein' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getMyFoods' : IDL.Func([], [IDL.Vec(FoodEntry)], ['query']),
  'getNutritionTotals' : IDL.Func([], [NutritionTotals], ['query']),
  'logFood' : IDL.Func([FoodEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const FoodEntry = IDL.Record({
    'fat' : IDL.Nat,
    'fiber' : IDL.Nat,
    'carbohydrates' : IDL.Nat,
    'calories' : IDL.Nat,
    'description' : IDL.Text,
    'timestamp' : Time,
    'protein' : IDL.Nat,
  });
  const NutritionTotals = IDL.Record({
    'fat' : IDL.Nat,
    'fiber' : IDL.Nat,
    'carbohydrates' : IDL.Nat,
    'calories' : IDL.Nat,
    'count' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  
  return IDL.Service({
    'getMyFoods' : IDL.Func([], [IDL.Vec(FoodEntry)], ['query']),
    'getNutritionTotals' : IDL.Func([], [NutritionTotals], ['query']),
    'logFood' : IDL.Func([FoodEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };