/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FoodEntry {
  'fat' : bigint,
  'fiber' : bigint,
  'carbohydrates' : bigint,
  'calories' : bigint,
  'description' : string,
  'timestamp' : Time,
  'protein' : bigint,
}
export interface NutritionTotals {
  'fat' : bigint,
  'fiber' : bigint,
  'carbohydrates' : bigint,
  'calories' : bigint,
  'count' : bigint,
  'protein' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  /**
   * / Retrieve all food entries for the caller, sorted by calories.
   */
  'getMyFoods' : ActorMethod<[], Array<FoodEntry>>,
  /**
   * / Compute aggregate nutrition totals for the caller's food entries.
   */
  'getNutritionTotals' : ActorMethod<[], NutritionTotals>,
  /**
   * / Log a new food entry for the caller.
   */
  'logFood' : ActorMethod<[FoodEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];